[font]
size = 6.20

[font.normal]
family = "JetBrains Mono Nerd Font"

[font.offset]
x = 0
y = 6

[colors.primary]
background = "0x000000" 
foreground = "0x888888"

[window]
dimensions = { columns = 80, lines = 24 }
